name = "MyRegistry"
uuid = "9e1cef36-1920-4a4c-9500-68a8af98ac64"
repo = "https://github.com/zhanghh0108/MyRegistry.git"
description = "My private registry"

[packages]
6c449bc8-684b-4d33-81ae-6aab8b76a314 = { name = "MyPackage4", path = "M/MyPackage4" }
b303c9e3-fd2a-4df6-8c6a-d018bc3a3699 = { name = "MyPackage3", path = "M/MyPackage3" }
